on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
          unzip android-ndk-r21d-linux-x86_64.zip
          echo "NDK=$(pwd)/android-ndk-r21d" >> $GITHUB_ENV

      - name: Build Go for Android ARM
        run: |
          CGO_ENABLED=1 \
          GOOS=android \
          GOARCH=arm \
          CC_FOR_TARGET=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
          go build -o bt-server

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: btserver
          path: btserver