on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cross-Compile
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: latest
          platforms: android/arm,android/arm64,android/386,android/amd64,ios/arm64,ios/amd64
          # platforms: linux/386,linux/amd64,linux/arm,linux/arm64,windows/386,windows/amd64,windows/arm,windows/arm64,ios/arm64,ios/amd64,darwin/amd64,darwin/arm64
          prefix: bt-server
          tags: ${{ github.ref_name }}
          v: true
          ldflags: -s -w
          dest: build

      - name: Rename Files
        run: |
          for file in build/*; do
            mv "$file" "${file/bt-server-/bt-server-${{ github.ref_name }}-}"
          done

      - name: Release Packages
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          allowUpdates: true
          omitBody: true
          tag: ${{ github.ref_name }}