on:
  push:
    tags:
      - v*

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
          - goos: android
            goarch: arm
          - goos: android
            goarch: arm64
          - goos: android
            goarch: 386
          - goos: android
            goarch: amd64

    steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.49
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        compress_assets: "OFF"
        cgo_enabled: "1"