on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cross-Compile
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: latest
          platforms: linux/386,linux/amd64,linux/arm,linux/arm64,windows/386,windows/amd64,windows/arm,windows/arm64,android-21/arm,android-21/arm64,android-21/386,android-21/amd64
          prefix: myproject
          v: true
          ldflags: -s -w
          dest: build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/
          