on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cross-Compile
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: latest
          platforms: linux/386,linux/amd64,linux/arm,linux/arm64,windows/386,windows/amd64,windows/arm,windows/arm64,android/arm,android/arm64,android/386,android/amd64
          prefix: bt-server
          tags: ${{ github.ref }}
          v: true
          ldflags: -s -w
          dest: build

      - name: Create Release and Upload Assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref }}
          prerelease: false
          title: 'Release ${{ github.ref }}'
          files: |
            build/*